### ISSUE TITLE
client losing network connection handling

### ISSUE THREAD

**Issue by KosmoGalaxy** [becvert/cordova-plugin-websocket-server#37] opened 2017-07-27 09:15 UTC
Android WebSocket client connects to the server. User goes away from the router and loses wifi connection. He comes back, connects back to wifi, but the server doesn't connect the new client - "open" event is not fired.

I don't know if "close" event fires. Both scenarios should be considered.

To make the client connect again, the server does not need to be restarted. Restarting wifi on the tablet with the server instantly corrects the problem.

Question aside. If the client is not closed after a period of "not being actually in the network anymore", how this situation should be handled?

**Comment by Abiraman** [comment] 2017-07-27 09:39
I posted #36 . Could you help me too?

**Comment by becvert** [comment] 2017-07-27 12:24
For me, when a client loses the wifi, most likely they receive a transport close error. and should discard the websocket and reconnect with a brand new websocket upon being back on the wifi.
Server side the socket may still be active until a ping timeout occurs in which case the server discard the socket as well.

> To make the client connect again

are you reconnecting with a new websocket?

**Comment by KosmoGalaxy** [comment] 2017-07-27 13:11
I'm connecting with a new websocket

**Comment by becvert** [comment] 2017-12-06 14:04
cannot reproduce. closing now.

**Closed as completed by becvert** 2017-12-06 14:04 UTC
