### ISSUE TITLE
Speed of response

### ISSUE THREAD

**Issue by ghost** [becvert/cordova-plugin-websocket-server#3] opened 2016-04-23 20:48 UTC
I'm sending a response to a client, but until that response arrives in the client, 3-6 seconds can have passed. Is this normal?

**Comment by becvert** [comment] 2016-04-23 21:15
Hi Wesley,
This is not normal of course.
What is your setup:
Is you server iOS or Android?
Is your client iOS or Android?

**Comment by ghost** [comment] 2016-04-23 21:19
Both server and client is ios, both are cordova apps. I added some logging, server receives immediately, sends immediately, but there appears to be a delay in receiving on the client ranging from 2-6 seconds. Both on same wifi, not overloaded by anything.

**Comment by becvert** [comment] 2016-04-23 21:26
OK. I'll have a look later on.
Anyone else experiencing the same thing?
Thanks.

**Comment by ghost** [comment] 2016-04-24 11:32
Seems to be an issue related to cordova webview? Here's the response times I get from a cordova app on ios iphone: 

2304
351
3714
6631
3063
773
5266
3210
483
114
1830
10347
5991
18340
8726
6034
336
60
5761

Yet when I run a test on my computer (simple websocket ping/pong), to the same ipad server, response times are all < 150...

**Comment by ghost** [comment] 2016-04-24 11:49
well i changed to wkwebview and that seems to have fixed the issue..

**Comment by ghost** [comment] 2016-04-24 14:52
actually, it's not fixed, just a little less. Still get up to 6 seconds delay. Server receives messages immediately, and "appears" to send a response immediately, but it only arrives after a significant delay.

**Comment by ghost** [comment] 2016-04-24 16:03
It may just be the ipad's speed.. It's an ipad 3. When I run it on the emulator via xcode, I have no slowdown. Seems the issue is the device itself. Though I did think a websocket server as this wouldn't have too high requirements.

**Comment by becvert** [comment] 2016-04-25 15:14
Hi Wesley,

I've done a quick test Between an iPhone 5 and iPad 2. It's working fine.
I assume the issue is with your device, your network or your app.
Are you doing a lot of GUI stuff on the client side?

I won't investigate further for now.
The next update will probably use the original PocketSocket (from [zwopple](https://github.com/zwopple/PocketSocket), not the fork from couchbasedeps ) as the author has done recent changes (after 2 years without commits). It might help you a bit.

This [discussion](http://stackoverflow.com/a/10883816) may help you too. Basically you need to add a timeout in the onmessage callback. Maybe it's irrelevant with a WkWebView though.

**Comment by ghost** [comment] 2016-04-25 15:17
No, I'm not doing much GUI stuff at all actually. Mind sharing your sample app? (If it's too much work, no need).

Though I do overwrite the onmessage handler a lot, that may have something to do with it maybe (as per your discussion link). Will check, thanks.

Anyway, looking forward to next version. thanks for your hard work.

**Comment by becvert** [comment] 2016-04-25 15:24
Unfortunately I do not have a sample app to share with you.
Let me now if the timeout in the handler fixes it.
Thank you

**Comment by ghost** [comment] 2016-04-25 17:09
timeout trick seems to work, most requests are now less than 300ms, some occassionally go to as far as 700ms, but nothing over that. Great! thanks for that tip.

**Comment by becvert** [comment] 2016-04-27 07:04
can we close this issue Wesley?

**Closed as completed** 2016-04-27 07:06 UTC
